[workspace]
resolver = "2"
members = [
  # Crates 
  "crates/tauri_fuzz_tools",
  # Examples
  "examples/mini-app/src-tauri",
  "examples/mini-app/src-tauri/fuzz",
]
exclude = ["LibAFL"]

[workspace.dependencies]
frida-gum = { version = "0.13.2", features = [
  "auto-download",
  "event-sink",
  "invocation-listener",
] }

libafl = { path = "./LibAFL/libafl", features = [
  "std",
  "llmp_compression",
  "llmp_bind_public",
  "frida_cli",
] } #,  "llmp_small_maps", "llmp_debug"]}
libafl_bolts = { path = "./LibAFL/libafl_bolts" }
libafl_frida = { path = "./LibAFL//libafl_frida", features = ["cmplog"] }
libafl_targets = { path = "./LibAFL/libafl_targets", features = [
  "sancov_cmplog",
] }
tauri_fuzz_tools = { path = "./crates/tauri_fuzz_tools" }

tauri = { version = "1.5", default-features = false, features = [
  "test",
  "tracing",
] }
tauri-runtime = "1.5"
tauri-build = "1.5"
tauri-utils = "1.5"
