[workspace]
resolver = "2"
members = [
  # Crates
  "crates/fuzzer",
  "crates/policies",
  "crates/cli",
  # Examples
  "examples/mini-app/src-tauri",
  # Tests
  "tests/fuzz-mini-app"
]
exclude = ["./crates/LibAFL"]

[workspace.dependencies]
# frida-gum = { path = "../frida-rust/frida-gum", features = [
#   "auto-download",
#   "event-sink",
#   "invocation-listener",
# ] }
frida-gum = { version = "0.13.2", features = [
  "auto-download",
  "event-sink",
  "invocation-listener",
] }

libafl = "0.13"
libafl_bolts = "0.13"
libafl_frida = {version = "0.13", features = ["cmplog"]}
libafl_targets = { version = "0.13", features = ["sancov_cmplog"]}

policies = { path = "./crates/policies" }
fuzzer = { path = "./crates/fuzzer" }
mini-app = { path = "./examples/mini-app/src-tauri" }

tauri = { version = "2.0.0-rc", features = ["test", "tracing"] }
tauri-runtime = { version = "2.0.0-rc", features = [] }
tauri-build = { version = "2.0.0-rc", features = [] }
tauri-utils = { version = "2.0.0-rc", features = [] }
tauri-plugin-fs = "2.0.0-rc"

# tauri = { path = "../tauri/crates/tauri", features = ["test", "tracing"] }
# tauri-runtime = { path = "../tauri/crates/tauri-runtime", features = [] }
# tauri-build = { path = "../tauri/crates/tauri-build", features = [] }
# tauri-utils = { path = "../tauri/crates/tauri-utils", features = [] }
# tauri-plugin-fs = { path = "../plugins-workspace/plugins/fs" }
