[workspace]
resolver = "2"
members = [
  # Crates 
  "crates/fuzzer",
  "crates/policies",
  # Examples
  "examples/mini-app/src-tauri",
  "examples/mini-app/src-tauri/fuzz",
]
exclude = ["./crates/LibAFL"]

[workspace.dependencies]
# frida-gum = { path = "../../tmp2/frida-rust/frida-gum", features = [
#   "auto-download",
#   "event-sink",
#   "invocation-listener",
# ] }
frida-gum = { version = "0.13.2", features = [
  "auto-download",
  "event-sink",
  "invocation-listener",
] }


libafl = { path = "./crates/LibAFL/libafl", features = [
  "std",
  "llmp_compression",
  "llmp_bind_public",
  "frida_cli",
] } #,  "llmp_small_maps", "llmp_debug"]}
libafl_bolts = { path = "./crates/LibAFL/libafl_bolts" }
libafl_frida = { path = "./crates/LibAFL/libafl_frida", features = ["cmplog"] }
libafl_targets = { path = "./crates/LibAFL/libafl_targets", features = [
  "sancov_cmplog",
] }
policies = { path = "./crates/policies" }
fuzzer = { path = "./crates/fuzzer" }

tauri = { version = "2.0.0-beta", features = ["test", "tracing"] }
tauri-runtime = { version = "2.0.0-beta", features = [] }
tauri-build = { version = "2.0.0-beta", features = [] }
tauri-utils = { version = "2.0.0-beta", features = [] }
tauri-plugin-fs = "2.0.0-beta"

# tauri = { path = "../../tmp2/tauri/core/tauri", features = ["test", "tracing"] }
# tauri-runtime = { path = "../../tmp2/tauri/core/tauri-runtime", features = [] }
# tauri-build = { path = "../../tmp2/tauri/core/tauri-build", features = [] }
# tauri-utils = { path = "../../tmp2/tauri/core/tauri-utils", features = [] }
# tauri-plugin-fs = { path = "../../tmp2/plugins-workspace/plugins/fs" }
