[workspace]
resolver = "2"
members = [
  "tauri_fuzz_tools",
  "mini-app/src-tauri",
  "mini-app/src-tauri/fuzz"
]

[workspace.dependencies]
libafl = { git = "ssh://git@github.com/crabnebula-dev/LibAFL.git", features = [ "std", "llmp_compression", "llmp_bind_public", "frida_cli" ], branch = "tauri" } #,  "llmp_small_maps", "llmp_debug"]}
libafl_bolts = { git = "ssh://git@github.com/crabnebula-dev/LibAFL.git", branch = "tauri" }
libafl_frida = { git = "ssh://git@github.com/crabnebula-dev/LibAFL.git", features = ["cmplog"], branch = "tauri" }
libafl_targets = { git = "ssh://git@github.com/crabnebula-dev/LibAFL.git", features = ["sancov_cmplog"], branch = "tauri" }
# libafl = { path = "../LibAFL/libafl", features = [ "std", "llmp_compression", "llmp_bind_public", "frida_cli" ] } #,  "llmp_small_maps", "llmp_debug"]}
# libafl_bolts = { path = "../LibAFL/libafl_bolts"}
# libafl_frida = { path = "../LibAFL/libafl_frida", features = ["cmplog"] }
# libafl_targets = { path = "../LibAFL/libafl_targets", features = ["sancov_cmplog"] }

[workspace.dependencies.tauri]
# path = "../tauri/core/tauri"
git = "ssh://git@github.com/crabnebula-dev/tauri.git"
branch = "feat/fuzz"
default-features = false
features = ["test"]

[workspace.dependencies.tauri-runtime]
# path = "../tauri/core/tauri-runtime"
git = "ssh://git@github.com/crabnebula-dev/tauri.git"
branch = "feat/fuzz"

[workspace.dependencies.tauri-build]
# path = "../tauri/core/tauri-build"
git = "ssh://git@github.com/crabnebula-dev/tauri.git"
branch = "feat/fuzz"




