[workspace]
resolver = "2"
members = [
  # Crates 
  "crates/fuzzer",
  "crates/policies",
  # Examples
  "examples/mini-app/src-tauri",
  "examples/mini-app/src-tauri/fuzz",
]
exclude = ["./crates/LibAFL"]

[workspace.dependencies]
frida-gum = { version = "0.13.2", features = [
  "auto-download",
  "event-sink",
  "invocation-listener",
] }

libafl = { path = "./crates/LibAFL/libafl", features = [
  "std",
  "llmp_compression",
  "llmp_bind_public",
  "frida_cli",
] } #,  "llmp_small_maps", "llmp_debug"]}
libafl_bolts = { path = "./crates/LibAFL/libafl_bolts" }
libafl_frida = { path = "./crates/LibAFL/libafl_frida", features = ["cmplog"] }
libafl_targets = { path = "./crates/LibAFL/libafl_targets", features = [
  "sancov_cmplog",
] }
policies = { path = "./crates/policies" }
fuzzer = { path = "./crates/fuzzer" }

tauri = { version = "2.0.0-beta", features = ["test", "tracing"] }
tauri-runtime = { version = "2.0.0-beta", features = [] }
tauri-build = { version = "2.0.0-beta", features = [] }
tauri-utils = { version = "2.0.0-beta", features = [] }
tauri-plugin-fs = "2.0.0-beta"
