[files]
extend-exclude = [
  "crates/LibAFL/*",
  "docs/presentation/plugin/*",
  "docs/presentation/images/*.svg",
  "/docs/presentation/dist/*",
  "/docs/presentation/test/",
  "*log"
]

[default.extend-identifiers]
FuzzND = "FuzzND"
laf = "laf"
