[files]
extend-exclude = ["LibAFL/*", "docs/presentation/plugin/*", "docs/presentation/images/*.svg", "/docs/presentation/dist/*", "/docs/presentation/test/"]

[default.extend-identifiers]
FuzzND = "FuzzND"
laf = "laf"
