[package]
name = "mini-app-fuzzer"
version = "0.10.0"
authors = []
edition = "2021"

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libafl = "0.10"
libafl_qemu = "0.10"
