[package]
name = "mini-app"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[lib]
# crate-type = ["dylib"]

[build-dependencies]
tauri-build = { version = "*", features = [] }

[dependencies]
log = "0.4"
env_logger = "*"

[dependencies.tauri]
path = "../../../tauri-for-fuzzy/core/tauri"
# git = "ssh://git@github.com/crabnebula-dev/tauri-for-fuzzy.git"
# branch = "1.5.1"
default-features = false
feature = ["fuzz"]

[dependencies.tauri-runtime]
path = "../../../tauri-for-fuzzy/core/tauri-runtime"
# git = "ssh://git@github.com/crabnebula-dev/tauri-for-fuzzy.git"
# branch = "1.5.1"
