[package]
name = "app-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[build-dependencies]
tauri-build = "1"

[dependencies]
app = { path = ".." }
tauri = { version = "1", features = ["api-all"] }
tauri-utils = "1"
fuzzer = { version = "*", features = ["tauri"] }
libafl = "*"
