name: Build and test

on: [pull_request]
#on:
  #push:
  #  branches: [ main, 'pr/**' ]
  #pull_request:
  #  branches: [ main ]
  #workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  common:
    strategy:
      matrix:
          os: [ubuntu-latest] #[ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install libgtk-3-dev
        run: sudo apt-get install -y libgtk-3-dev
        
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - uses: actions/checkout@v4
        name: Checkout repository
        #with:
        # ssh-key: |
        #    ${{ secrets.REPO_READ_KEY }}
        #    ${{ secrets.LIBAFL_SUBMODULE_KEY }}
        # submodules: recursive

      - name: Add SSH private key for submodule repositorie
        uses: webfactory/ssh-agent@v0.9.0
        with:
           ssh-private-key: ${{ secrets.LIBAFL_SUBMODULE_KEY }}
      
        ## Maybe use this instead https://github.com/actions/checkout/issues/287#issuecomment-1830291196
      - name: Checkout Submodule
        run: git submodule update --init --recursive

      - name: Install mdbook
        run: cargo install mdbook mdbook-toc mdbook-linkcheck

      - name: Build the book
        run: cd docs && mdbook build

      - name: Build debug
        run: cargo build
#      - name: Test the book
#        # TODO: fix books test fail with updated windows-rs
#        run: cd docs && mdbook test -L ../target/debug/deps
      - name: Run tests
        run: cargo test
